format = """
$username\
$hostname\
$directory\
$python\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration $jobs $time\
$line_break\
$character"""

add_newline = true

[directory]
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "

[python]
symbol = '👾 '

[line_break]
disabled = false
